name: GraalVM Gate

on:
  push:
    branches:
      - 'master'
      - 'release/**'
    paths-ignore:
      - '.devcontainer/**'
      - '.github/workflows/quarkus.yml'
      - '**.md'
      - '**.jsonnet'
      - '**.libjsonnet'
  pull_request:
    paths-ignore:
      - '.devcontainer/**'
      - '.github/workflows/quarkus.yml'
      - '**.md'
      - '**.jsonnet'
      - '**.libjsonnet'
  # Enable manual dispatch of the workflow
  # see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

# The following aims to reduce CI CPU cycles by:
# 1. Cancelling any previous builds of this PR when pushing new changes to it
# 2. Cancelling any previous builds of a branch when pushing new changes to it in a fork
# 3. Cancelling any pending builds, but not active ones, when pushing to a branch in the main
#    repository. This prevents us from constantly cancelling CI runs, while being able to skip
#    intermediate builds. E.g., if we perform two pushes the first one will start a CI job and
#    the second one will add another one to the queue; if we perform a third push while the
#    first CI job is still running the previously queued CI job (for the second push) will be
#    cancelled and a new CI job will be queued for the latest (third) push.
concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'oracle/graal' }}

env:
  JAVA_HOME: ${{ github.workspace }}/jdk
  JDT: builtin
  LANG: en_US.UTF-8
  MX_GATE_OPTS: "--strict-mode"
  MX_GIT_CACHE: refcache
  MX_PATH: ${{ github.workspace }}/mx
  MX_PYTHON: python3.8

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-graalvm:
    name: ${{ matrix.env.PRIMARY }} ${{ matrix.env.GATE }} JDK${{ matrix.env.JDK_VERSION }} ${{ matrix.env.WITHOUT_VCS }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # /compiler
          - env:
              JDK_VERSION: "19"
              GATE: "style,fullbuild,test"
              PRIMARY: "compiler"
          - env:
              JDK_VERSION: "19"
              GATE: "build,bootstraplite"
              PRIMARY: "compiler"
          # /espresso
          - env:
              JDK_VERSION: "17" # espresso does not support JDK19 yet
              GATE: "style,fullbuild"
              PRIMARY: "espresso"
          # /substratevm
          - env:
              JDK_VERSION: "19"
              GATE: "style,fullbuild"
              PRIMARY: "substratevm"
          - env:
              JDK_VERSION: "19"
              GATE: "build,test,helloworld"
              PRIMARY: "substratevm"
          - env:
              JDK_VERSION: "19"
              GATE: "build,test,helloworld_debug"
              PRIMARY: "substratevm"
          - env:
              JDK_VERSION: "19"
              GATE: "build,debuginfotest"
              PRIMARY: "substratevm"
          - env:
              JDK_VERSION: "19"
              GATE: "hellomodule"
              PRIMARY: "substratevm"
          # /sulong
          - env:
              JDK_VERSION: "19"
              GATE: "style,fullbuild,sulongBasic"
              MX_GATE_OPTS: "--strict-mode --no-warning-as-error" # sulong throws deprecation warnings
              PRIMARY: "sulong"
          # /vm
          - env:
              JDK_VERSION: "19"
              GATE: "build,sulong"
              MX_GATE_OPTS: "--strict-mode --no-warning-as-error" # sulong throws deprecation warnings
              PRIMARY: "vm"
              DYNAMIC_IMPORTS: "/sulong,/substratevm"
              DISABLE_POLYGLOT: true
              DISABLE_LIBPOLYGLOT: true
          - env:
              JDK_VERSION: "17"
              GATE: "build"
              PRIMARY: "vm"
              DYNAMIC_IMPORTS: "/tools,/substratevm,/sulong"
              NATIVE_IMAGES: "polyglot"
              WITHOUT_VCS: true
    steps:
    - name: Checkout oracle/graal
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }} # Lock ref to current branch to avoid fetching others
        fetch-depth: "${{ contains(matrix.env.GATE, 'style') && '0' || '1' }}" # The style gate needs the full commit history for checking copyright years
    - name: Determine mx version
      run: echo "MX_VERSION=$(jq -r '.mx_version' common.json)" >> ${GITHUB_ENV}
    - name: Checkout graalvm/mx
      uses: actions/checkout@v3
      with:
        repository: graalvm/mx.git
        ref: ${{ env.MX_VERSION }}
        fetch-depth: 1
        path: ${{ env.MX_PATH }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Update mx cache
      uses: actions/cache@v3
      with:
        path: ~/.mx
        key: ${{ runner.os }}-mx-${{ hashFiles('**/suite.py') }}
        restore-keys: ${{ runner.os }}-mx-
    - name: Fetch LabsJDK
      env: ${{ matrix.env }}
      run: |
        mkdir jdk-dl
        ${MX_PATH}/mx --java-home= fetch-jdk --jdk-id labsjdk-ce-${JDK_VERSION} --to jdk-dl --alias ${JAVA_HOME}
    - name: Update dependency cache
      if: ${{ contains(matrix.env.GATE, 'debug') || contains(matrix.env.GATE, 'style') }}
      run: sudo apt update
    - name: Install debug dependencies
      if: ${{ contains(matrix.env.GATE, 'debug') }}
      run: sudo apt install gdb
    - name: Install style dependencies
      if: ${{ contains(matrix.env.GATE, 'style') }}
      run: |
        sudo apt install python3-pip python-setuptools
        jq -r '.deps.common.packages | to_entries[] | select(.key | startswith("pip:")) | (.key | split(":")[1]) + .value' common.json |
          xargs sudo pip install
        ${MX_PYTHON} -m pip install jsonschema==4.6.1
    - name: Download Eclipse
      if: ${{ contains(matrix.env.GATE, 'style') }}
      run: |
        ECLIPSE_TAR=eclipse.tar.gz
        ECLIPSE_ORG_VERSION=$(jq -r '.downloads.eclipse.eclipse_org.version' common.json)
        ECLIPSE_ORG_TIMESTAMP=$(jq -r '.downloads.eclipse.eclipse_org.timestamp' common.json)
        wget --no-verbose https://archive.eclipse.org/eclipse/downloads/drops4/R-${ECLIPSE_ORG_VERSION}-${ECLIPSE_ORG_TIMESTAMP}/eclipse-SDK-${ECLIPSE_ORG_VERSION}-linux-gtk-x86_64.tar.gz -O $ECLIPSE_TAR
        tar -xzf ${ECLIPSE_TAR}
        echo "ECLIPSE_EXE=${PWD}/eclipse/eclipse" >> $GITHUB_ENV
    - name: Remove .git directory
      if: ${{ matrix.env.WITHOUT_VCS }}
      run: rm -rf .git
    - name: Build GraalVM and run gate
      env: ${{ matrix.env }}
      run: ${MX_PATH}/mx --primary-suite-path ${PRIMARY} --java-home=${JAVA_HOME} gate ${MX_GATE_OPTS} --tags ${GATE}
